/********************************************************************************
** Form generated from reading UI file 'sudokumaster.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SUDOKUMASTER_H
#define UI_SUDOKUMASTER_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SudokuMaster
{
public:
    QWidget *centralwidget;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QLineEdit *lineEdit_0_0;
    QLineEdit *lineEdit_0_2;
    QLineEdit *lineEdit_0_3;
    QLineEdit *lineEdit_0_4;
    QLineEdit *lineEdit_0_5;
    QLineEdit *lineEdit_0_6;
    QLineEdit *lineEdit_0_7;
    QLineEdit *lineEdit_0_8;
    QLineEdit *lineEdit_1_0;
    QLineEdit *lineEdit_1_1;
    QLineEdit *lineEdit_1_2;
    QLineEdit *lineEdit_2_0;
    QLineEdit *lineEdit_2_1;
    QLineEdit *lineEdit_2_2;
    QLineEdit *lineEdit_1_3;
    QLineEdit *lineEdit_1_4;
    QLineEdit *lineEdit_1_5;
    QLineEdit *lineEdit_2_3;
    QLineEdit *lineEdit_2_4;
    QLineEdit *lineEdit_2_5;
    QLineEdit *lineEdit_1_6;
    QLineEdit *lineEdit_1_7;
    QLineEdit *lineEdit_1_8;
    QLineEdit *lineEdit_2_6;
    QLineEdit *lineEdit_2_7;
    QLineEdit *lineEdit_2_8;
    QLineEdit *lineEdit_3_0;
    QLineEdit *lineEdit_3_1;
    QLineEdit *lineEdit_3_2;
    QLineEdit *lineEdit_3_3;
    QLineEdit *lineEdit_4_2;
    QLineEdit *lineEdit_4_4;
    QLineEdit *lineEdit_4_1;
    QLineEdit *lineEdit_4_6;
    QLineEdit *lineEdit_4_7;
    QLineEdit *lineEdit_4_3;
    QLineEdit *lineEdit_4_5;
    QLineEdit *lineEdit_4_0;
    QLineEdit *lineEdit_4_8;
    QLineEdit *lineEdit_5_2;
    QLineEdit *lineEdit_5_4;
    QLineEdit *lineEdit_5_1;
    QLineEdit *lineEdit_5_6;
    QLineEdit *lineEdit_5_7;
    QLineEdit *lineEdit_5_3;
    QLineEdit *lineEdit_5_5;
    QLineEdit *lineEdit_5_0;
    QLineEdit *lineEdit_5_8;
    QLineEdit *lineEdit_6_2;
    QLineEdit *lineEdit_6_4;
    QLineEdit *lineEdit_6_1;
    QLineEdit *lineEdit_6_6;
    QLineEdit *lineEdit_6_7;
    QLineEdit *lineEdit_6_3;
    QLineEdit *lineEdit_6_5;
    QLineEdit *lineEdit_6_0;
    QLineEdit *lineEdit_6_8;
    QLineEdit *lineEdit_7_2;
    QLineEdit *lineEdit_7_4;
    QLineEdit *lineEdit_7_1;
    QLineEdit *lineEdit_7_6;
    QLineEdit *lineEdit_7_7;
    QLineEdit *lineEdit_7_3;
    QLineEdit *lineEdit_7_5;
    QLineEdit *lineEdit_7_0;
    QLineEdit *lineEdit_7_8;
    QLineEdit *lineEdit_8_2;
    QLineEdit *lineEdit_8_4;
    QLineEdit *lineEdit_8_1;
    QLineEdit *lineEdit_8_6;
    QLineEdit *lineEdit_8_7;
    QLineEdit *lineEdit_8_3;
    QLineEdit *lineEdit_8_5;
    QLineEdit *lineEdit_8_0;
    QLineEdit *lineEdit_8_8;
    QLineEdit *lineEdit_3_7;
    QLineEdit *lineEdit_3_5;
    QLineEdit *lineEdit_3_6;
    QLineEdit *lineEdit_3_4;
    QLineEdit *lineEdit_3_8;
    QLineEdit *lineEdit_0_1;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *SudokuMaster)
    {
        if (SudokuMaster->objectName().isEmpty())
            SudokuMaster->setObjectName("SudokuMaster");
        SudokuMaster->resize(930, 933);
        centralwidget = new QWidget(SudokuMaster);
        centralwidget->setObjectName("centralwidget");
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName("line_2");
        line_2->setGeometry(QRect(140, 40, 20, 811));
        line_2->setLineWidth(2);
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(230, 40, 20, 811));
        line_3->setLineWidth(2);
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName("line_4");
        line_4->setGeometry(QRect(320, 40, 20, 811));
        QFont font;
        font.setBold(true);
        line_4->setFont(font);
        line_4->setLineWidth(4);
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName("line_5");
        line_5->setGeometry(QRect(410, 40, 20, 811));
        line_5->setLineWidth(2);
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName("line_6");
        line_6->setGeometry(QRect(500, 40, 20, 811));
        line_6->setLineWidth(2);
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName("line_7");
        line_7->setGeometry(QRect(590, 40, 20, 811));
        line_7->setFont(font);
        line_7->setLineWidth(4);
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralwidget);
        line_8->setObjectName("line_8");
        line_8->setGeometry(QRect(860, 40, 20, 811));
        line_8->setLineWidth(4);
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralwidget);
        line_9->setObjectName("line_9");
        line_9->setGeometry(QRect(680, 40, 21, 811));
        line_9->setLineWidth(2);
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralwidget);
        line_10->setObjectName("line_10");
        line_10->setGeometry(QRect(50, 40, 20, 811));
        line_10->setLineWidth(4);
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralwidget);
        line_11->setObjectName("line_11");
        line_11->setGeometry(QRect(60, 210, 811, 20));
        QFont font1;
        font1.setPointSize(13);
        line_11->setFont(font1);
        line_11->setLineWidth(2);
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralwidget);
        line_12->setObjectName("line_12");
        line_12->setGeometry(QRect(60, 30, 811, 20));
        line_12->setFont(font1);
        line_12->setLineWidth(4);
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(centralwidget);
        line_13->setObjectName("line_13");
        line_13->setGeometry(QRect(60, 300, 811, 20));
        QFont font2;
        font2.setPointSize(13);
        font2.setBold(true);
        font2.setStrikeOut(false);
        line_13->setFont(font2);
        line_13->setLineWidth(4);
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralwidget);
        line_14->setObjectName("line_14");
        line_14->setGeometry(QRect(770, 40, 21, 811));
        line_14->setLineWidth(2);
        line_14->setFrameShape(QFrame::VLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line = new QFrame(centralwidget);
        line->setObjectName("line");
        line->setGeometry(QRect(60, 120, 811, 20));
        line->setFont(font1);
        line->setLineWidth(2);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(centralwidget);
        line_15->setObjectName("line_15");
        line_15->setGeometry(QRect(60, 390, 811, 20));
        line_15->setFont(font1);
        line_15->setLineWidth(2);
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(centralwidget);
        line_16->setObjectName("line_16");
        line_16->setGeometry(QRect(60, 480, 811, 20));
        line_16->setFont(font1);
        line_16->setLineWidth(2);
        line_16->setFrameShape(QFrame::HLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(centralwidget);
        line_17->setObjectName("line_17");
        line_17->setGeometry(QRect(60, 570, 811, 20));
        QFont font3;
        font3.setPointSize(13);
        font3.setBold(true);
        line_17->setFont(font3);
        line_17->setLineWidth(4);
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(centralwidget);
        line_18->setObjectName("line_18");
        line_18->setGeometry(QRect(60, 660, 811, 20));
        line_18->setFont(font1);
        line_18->setLineWidth(2);
        line_18->setFrameShape(QFrame::HLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(centralwidget);
        line_19->setObjectName("line_19");
        line_19->setGeometry(QRect(60, 750, 811, 20));
        line_19->setFont(font1);
        line_19->setLineWidth(2);
        line_19->setFrameShape(QFrame::HLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(centralwidget);
        line_20->setObjectName("line_20");
        line_20->setGeometry(QRect(60, 840, 811, 20));
        line_20->setFont(font1);
        line_20->setLineWidth(4);
        line_20->setFrameShape(QFrame::HLine);
        line_20->setFrameShadow(QFrame::Sunken);
        lineEdit_0_0 = new QLineEdit(centralwidget);
        lineEdit_0_0->setObjectName("lineEdit_0_0");
        lineEdit_0_0->setGeometry(QRect(60, 40, 91, 91));
        QFont font4;
        font4.setPointSize(25);
        lineEdit_0_0->setFont(font4);
        lineEdit_0_0->setMaxLength(1);
        lineEdit_0_0->setAlignment(Qt::AlignCenter);
        lineEdit_0_2 = new QLineEdit(centralwidget);
        lineEdit_0_2->setObjectName("lineEdit_0_2");
        lineEdit_0_2->setGeometry(QRect(240, 40, 91, 91));
        lineEdit_0_2->setFont(font4);
        lineEdit_0_2->setMaxLength(1);
        lineEdit_0_2->setAlignment(Qt::AlignCenter);
        lineEdit_0_3 = new QLineEdit(centralwidget);
        lineEdit_0_3->setObjectName("lineEdit_0_3");
        lineEdit_0_3->setGeometry(QRect(330, 40, 91, 91));
        lineEdit_0_3->setFont(font4);
        lineEdit_0_3->setMaxLength(1);
        lineEdit_0_3->setAlignment(Qt::AlignCenter);
        lineEdit_0_4 = new QLineEdit(centralwidget);
        lineEdit_0_4->setObjectName("lineEdit_0_4");
        lineEdit_0_4->setGeometry(QRect(420, 40, 91, 91));
        lineEdit_0_4->setFont(font4);
        lineEdit_0_4->setMaxLength(1);
        lineEdit_0_4->setAlignment(Qt::AlignCenter);
        lineEdit_0_5 = new QLineEdit(centralwidget);
        lineEdit_0_5->setObjectName("lineEdit_0_5");
        lineEdit_0_5->setGeometry(QRect(510, 40, 91, 91));
        lineEdit_0_5->setFont(font4);
        lineEdit_0_5->setMaxLength(1);
        lineEdit_0_5->setAlignment(Qt::AlignCenter);
        lineEdit_0_6 = new QLineEdit(centralwidget);
        lineEdit_0_6->setObjectName("lineEdit_0_6");
        lineEdit_0_6->setGeometry(QRect(600, 40, 91, 91));
        lineEdit_0_6->setFont(font4);
        lineEdit_0_6->setMaxLength(1);
        lineEdit_0_6->setAlignment(Qt::AlignCenter);
        lineEdit_0_7 = new QLineEdit(centralwidget);
        lineEdit_0_7->setObjectName("lineEdit_0_7");
        lineEdit_0_7->setGeometry(QRect(690, 40, 91, 91));
        lineEdit_0_7->setFont(font4);
        lineEdit_0_7->setMaxLength(1);
        lineEdit_0_7->setAlignment(Qt::AlignCenter);
        lineEdit_0_8 = new QLineEdit(centralwidget);
        lineEdit_0_8->setObjectName("lineEdit_0_8");
        lineEdit_0_8->setGeometry(QRect(780, 40, 91, 91));
        lineEdit_0_8->setFont(font4);
        lineEdit_0_8->setMaxLength(1);
        lineEdit_0_8->setAlignment(Qt::AlignCenter);
        lineEdit_1_0 = new QLineEdit(centralwidget);
        lineEdit_1_0->setObjectName("lineEdit_1_0");
        lineEdit_1_0->setGeometry(QRect(60, 130, 91, 91));
        lineEdit_1_0->setFont(font4);
        lineEdit_1_0->setMaxLength(1);
        lineEdit_1_0->setAlignment(Qt::AlignCenter);
        lineEdit_1_1 = new QLineEdit(centralwidget);
        lineEdit_1_1->setObjectName("lineEdit_1_1");
        lineEdit_1_1->setGeometry(QRect(150, 130, 91, 91));
        lineEdit_1_1->setFont(font4);
        lineEdit_1_1->setMaxLength(1);
        lineEdit_1_1->setAlignment(Qt::AlignCenter);
        lineEdit_1_2 = new QLineEdit(centralwidget);
        lineEdit_1_2->setObjectName("lineEdit_1_2");
        lineEdit_1_2->setGeometry(QRect(240, 130, 91, 91));
        lineEdit_1_2->setFont(font4);
        lineEdit_1_2->setMaxLength(1);
        lineEdit_1_2->setAlignment(Qt::AlignCenter);
        lineEdit_2_0 = new QLineEdit(centralwidget);
        lineEdit_2_0->setObjectName("lineEdit_2_0");
        lineEdit_2_0->setGeometry(QRect(60, 220, 91, 91));
        lineEdit_2_0->setFont(font4);
        lineEdit_2_0->setMaxLength(1);
        lineEdit_2_0->setAlignment(Qt::AlignCenter);
        lineEdit_2_1 = new QLineEdit(centralwidget);
        lineEdit_2_1->setObjectName("lineEdit_2_1");
        lineEdit_2_1->setGeometry(QRect(150, 220, 91, 91));
        lineEdit_2_1->setFont(font4);
        lineEdit_2_1->setMaxLength(1);
        lineEdit_2_1->setAlignment(Qt::AlignCenter);
        lineEdit_2_2 = new QLineEdit(centralwidget);
        lineEdit_2_2->setObjectName("lineEdit_2_2");
        lineEdit_2_2->setGeometry(QRect(240, 220, 91, 91));
        lineEdit_2_2->setFont(font4);
        lineEdit_2_2->setMaxLength(1);
        lineEdit_2_2->setAlignment(Qt::AlignCenter);
        lineEdit_1_3 = new QLineEdit(centralwidget);
        lineEdit_1_3->setObjectName("lineEdit_1_3");
        lineEdit_1_3->setGeometry(QRect(330, 130, 91, 91));
        lineEdit_1_3->setFont(font4);
        lineEdit_1_3->setMaxLength(1);
        lineEdit_1_3->setAlignment(Qt::AlignCenter);
        lineEdit_1_4 = new QLineEdit(centralwidget);
        lineEdit_1_4->setObjectName("lineEdit_1_4");
        lineEdit_1_4->setGeometry(QRect(420, 130, 91, 91));
        lineEdit_1_4->setFont(font4);
        lineEdit_1_4->setMaxLength(1);
        lineEdit_1_4->setAlignment(Qt::AlignCenter);
        lineEdit_1_5 = new QLineEdit(centralwidget);
        lineEdit_1_5->setObjectName("lineEdit_1_5");
        lineEdit_1_5->setGeometry(QRect(510, 130, 91, 91));
        lineEdit_1_5->setFont(font4);
        lineEdit_1_5->setMaxLength(1);
        lineEdit_1_5->setAlignment(Qt::AlignCenter);
        lineEdit_2_3 = new QLineEdit(centralwidget);
        lineEdit_2_3->setObjectName("lineEdit_2_3");
        lineEdit_2_3->setGeometry(QRect(330, 220, 91, 91));
        lineEdit_2_3->setFont(font4);
        lineEdit_2_3->setMaxLength(1);
        lineEdit_2_3->setAlignment(Qt::AlignCenter);
        lineEdit_2_4 = new QLineEdit(centralwidget);
        lineEdit_2_4->setObjectName("lineEdit_2_4");
        lineEdit_2_4->setGeometry(QRect(420, 220, 91, 91));
        lineEdit_2_4->setFont(font4);
        lineEdit_2_4->setMaxLength(1);
        lineEdit_2_4->setAlignment(Qt::AlignCenter);
        lineEdit_2_5 = new QLineEdit(centralwidget);
        lineEdit_2_5->setObjectName("lineEdit_2_5");
        lineEdit_2_5->setGeometry(QRect(510, 220, 91, 91));
        lineEdit_2_5->setFont(font4);
        lineEdit_2_5->setMaxLength(1);
        lineEdit_2_5->setAlignment(Qt::AlignCenter);
        lineEdit_1_6 = new QLineEdit(centralwidget);
        lineEdit_1_6->setObjectName("lineEdit_1_6");
        lineEdit_1_6->setGeometry(QRect(600, 130, 91, 91));
        lineEdit_1_6->setFont(font4);
        lineEdit_1_6->setMaxLength(1);
        lineEdit_1_6->setAlignment(Qt::AlignCenter);
        lineEdit_1_7 = new QLineEdit(centralwidget);
        lineEdit_1_7->setObjectName("lineEdit_1_7");
        lineEdit_1_7->setGeometry(QRect(690, 130, 91, 91));
        lineEdit_1_7->setFont(font4);
        lineEdit_1_7->setMaxLength(1);
        lineEdit_1_7->setAlignment(Qt::AlignCenter);
        lineEdit_1_8 = new QLineEdit(centralwidget);
        lineEdit_1_8->setObjectName("lineEdit_1_8");
        lineEdit_1_8->setGeometry(QRect(780, 130, 91, 91));
        lineEdit_1_8->setFont(font4);
        lineEdit_1_8->setMaxLength(1);
        lineEdit_1_8->setAlignment(Qt::AlignCenter);
        lineEdit_2_6 = new QLineEdit(centralwidget);
        lineEdit_2_6->setObjectName("lineEdit_2_6");
        lineEdit_2_6->setGeometry(QRect(600, 220, 91, 91));
        lineEdit_2_6->setFont(font4);
        lineEdit_2_6->setMaxLength(1);
        lineEdit_2_6->setAlignment(Qt::AlignCenter);
        lineEdit_2_7 = new QLineEdit(centralwidget);
        lineEdit_2_7->setObjectName("lineEdit_2_7");
        lineEdit_2_7->setGeometry(QRect(690, 220, 91, 91));
        lineEdit_2_7->setFont(font4);
        lineEdit_2_7->setMaxLength(1);
        lineEdit_2_7->setAlignment(Qt::AlignCenter);
        lineEdit_2_8 = new QLineEdit(centralwidget);
        lineEdit_2_8->setObjectName("lineEdit_2_8");
        lineEdit_2_8->setGeometry(QRect(780, 220, 91, 91));
        lineEdit_2_8->setFont(font4);
        lineEdit_2_8->setMaxLength(1);
        lineEdit_2_8->setAlignment(Qt::AlignCenter);
        lineEdit_3_0 = new QLineEdit(centralwidget);
        lineEdit_3_0->setObjectName("lineEdit_3_0");
        lineEdit_3_0->setGeometry(QRect(60, 310, 91, 91));
        lineEdit_3_0->setFont(font4);
        lineEdit_3_0->setMaxLength(1);
        lineEdit_3_0->setAlignment(Qt::AlignCenter);
        lineEdit_3_1 = new QLineEdit(centralwidget);
        lineEdit_3_1->setObjectName("lineEdit_3_1");
        lineEdit_3_1->setGeometry(QRect(150, 310, 91, 91));
        lineEdit_3_1->setFont(font4);
        lineEdit_3_1->setMaxLength(1);
        lineEdit_3_1->setAlignment(Qt::AlignCenter);
        lineEdit_3_2 = new QLineEdit(centralwidget);
        lineEdit_3_2->setObjectName("lineEdit_3_2");
        lineEdit_3_2->setGeometry(QRect(240, 310, 91, 91));
        lineEdit_3_2->setFont(font4);
        lineEdit_3_2->setMaxLength(1);
        lineEdit_3_2->setAlignment(Qt::AlignCenter);
        lineEdit_3_3 = new QLineEdit(centralwidget);
        lineEdit_3_3->setObjectName("lineEdit_3_3");
        lineEdit_3_3->setGeometry(QRect(330, 310, 91, 91));
        lineEdit_3_3->setFont(font4);
        lineEdit_3_3->setMaxLength(1);
        lineEdit_3_3->setAlignment(Qt::AlignCenter);
        lineEdit_4_2 = new QLineEdit(centralwidget);
        lineEdit_4_2->setObjectName("lineEdit_4_2");
        lineEdit_4_2->setGeometry(QRect(240, 400, 91, 91));
        lineEdit_4_2->setFont(font4);
        lineEdit_4_2->setMaxLength(1);
        lineEdit_4_2->setAlignment(Qt::AlignCenter);
        lineEdit_4_4 = new QLineEdit(centralwidget);
        lineEdit_4_4->setObjectName("lineEdit_4_4");
        lineEdit_4_4->setGeometry(QRect(420, 400, 91, 91));
        lineEdit_4_4->setFont(font4);
        lineEdit_4_4->setMaxLength(1);
        lineEdit_4_4->setAlignment(Qt::AlignCenter);
        lineEdit_4_1 = new QLineEdit(centralwidget);
        lineEdit_4_1->setObjectName("lineEdit_4_1");
        lineEdit_4_1->setGeometry(QRect(150, 400, 91, 91));
        lineEdit_4_1->setFont(font4);
        lineEdit_4_1->setMaxLength(1);
        lineEdit_4_1->setAlignment(Qt::AlignCenter);
        lineEdit_4_6 = new QLineEdit(centralwidget);
        lineEdit_4_6->setObjectName("lineEdit_4_6");
        lineEdit_4_6->setGeometry(QRect(600, 400, 91, 91));
        lineEdit_4_6->setFont(font4);
        lineEdit_4_6->setMaxLength(1);
        lineEdit_4_6->setAlignment(Qt::AlignCenter);
        lineEdit_4_7 = new QLineEdit(centralwidget);
        lineEdit_4_7->setObjectName("lineEdit_4_7");
        lineEdit_4_7->setGeometry(QRect(690, 400, 91, 91));
        lineEdit_4_7->setFont(font4);
        lineEdit_4_7->setMaxLength(1);
        lineEdit_4_7->setAlignment(Qt::AlignCenter);
        lineEdit_4_3 = new QLineEdit(centralwidget);
        lineEdit_4_3->setObjectName("lineEdit_4_3");
        lineEdit_4_3->setGeometry(QRect(330, 400, 91, 91));
        lineEdit_4_3->setFont(font4);
        lineEdit_4_3->setMaxLength(1);
        lineEdit_4_3->setAlignment(Qt::AlignCenter);
        lineEdit_4_5 = new QLineEdit(centralwidget);
        lineEdit_4_5->setObjectName("lineEdit_4_5");
        lineEdit_4_5->setGeometry(QRect(510, 400, 91, 91));
        lineEdit_4_5->setFont(font4);
        lineEdit_4_5->setMaxLength(1);
        lineEdit_4_5->setAlignment(Qt::AlignCenter);
        lineEdit_4_0 = new QLineEdit(centralwidget);
        lineEdit_4_0->setObjectName("lineEdit_4_0");
        lineEdit_4_0->setGeometry(QRect(60, 400, 91, 91));
        lineEdit_4_0->setFont(font4);
        lineEdit_4_0->setMaxLength(1);
        lineEdit_4_0->setAlignment(Qt::AlignCenter);
        lineEdit_4_8 = new QLineEdit(centralwidget);
        lineEdit_4_8->setObjectName("lineEdit_4_8");
        lineEdit_4_8->setGeometry(QRect(780, 400, 91, 91));
        lineEdit_4_8->setFont(font4);
        lineEdit_4_8->setMaxLength(1);
        lineEdit_4_8->setAlignment(Qt::AlignCenter);
        lineEdit_5_2 = new QLineEdit(centralwidget);
        lineEdit_5_2->setObjectName("lineEdit_5_2");
        lineEdit_5_2->setGeometry(QRect(240, 490, 91, 91));
        lineEdit_5_2->setFont(font4);
        lineEdit_5_2->setMaxLength(1);
        lineEdit_5_2->setAlignment(Qt::AlignCenter);
        lineEdit_5_4 = new QLineEdit(centralwidget);
        lineEdit_5_4->setObjectName("lineEdit_5_4");
        lineEdit_5_4->setGeometry(QRect(420, 490, 91, 91));
        lineEdit_5_4->setFont(font4);
        lineEdit_5_4->setMaxLength(1);
        lineEdit_5_4->setAlignment(Qt::AlignCenter);
        lineEdit_5_1 = new QLineEdit(centralwidget);
        lineEdit_5_1->setObjectName("lineEdit_5_1");
        lineEdit_5_1->setGeometry(QRect(150, 490, 91, 91));
        lineEdit_5_1->setFont(font4);
        lineEdit_5_1->setMaxLength(1);
        lineEdit_5_1->setAlignment(Qt::AlignCenter);
        lineEdit_5_6 = new QLineEdit(centralwidget);
        lineEdit_5_6->setObjectName("lineEdit_5_6");
        lineEdit_5_6->setGeometry(QRect(600, 490, 91, 91));
        lineEdit_5_6->setFont(font4);
        lineEdit_5_6->setMaxLength(1);
        lineEdit_5_6->setAlignment(Qt::AlignCenter);
        lineEdit_5_7 = new QLineEdit(centralwidget);
        lineEdit_5_7->setObjectName("lineEdit_5_7");
        lineEdit_5_7->setGeometry(QRect(690, 490, 91, 91));
        lineEdit_5_7->setFont(font4);
        lineEdit_5_7->setMaxLength(1);
        lineEdit_5_7->setAlignment(Qt::AlignCenter);
        lineEdit_5_3 = new QLineEdit(centralwidget);
        lineEdit_5_3->setObjectName("lineEdit_5_3");
        lineEdit_5_3->setGeometry(QRect(330, 490, 91, 91));
        lineEdit_5_3->setFont(font4);
        lineEdit_5_3->setMaxLength(1);
        lineEdit_5_3->setAlignment(Qt::AlignCenter);
        lineEdit_5_5 = new QLineEdit(centralwidget);
        lineEdit_5_5->setObjectName("lineEdit_5_5");
        lineEdit_5_5->setGeometry(QRect(510, 490, 91, 91));
        lineEdit_5_5->setFont(font4);
        lineEdit_5_5->setMaxLength(1);
        lineEdit_5_5->setAlignment(Qt::AlignCenter);
        lineEdit_5_0 = new QLineEdit(centralwidget);
        lineEdit_5_0->setObjectName("lineEdit_5_0");
        lineEdit_5_0->setGeometry(QRect(60, 490, 91, 91));
        lineEdit_5_0->setFont(font4);
        lineEdit_5_0->setMaxLength(1);
        lineEdit_5_0->setAlignment(Qt::AlignCenter);
        lineEdit_5_8 = new QLineEdit(centralwidget);
        lineEdit_5_8->setObjectName("lineEdit_5_8");
        lineEdit_5_8->setGeometry(QRect(780, 490, 91, 91));
        lineEdit_5_8->setFont(font4);
        lineEdit_5_8->setMaxLength(1);
        lineEdit_5_8->setAlignment(Qt::AlignCenter);
        lineEdit_6_2 = new QLineEdit(centralwidget);
        lineEdit_6_2->setObjectName("lineEdit_6_2");
        lineEdit_6_2->setGeometry(QRect(240, 580, 91, 91));
        lineEdit_6_2->setFont(font4);
        lineEdit_6_2->setMaxLength(1);
        lineEdit_6_2->setAlignment(Qt::AlignCenter);
        lineEdit_6_4 = new QLineEdit(centralwidget);
        lineEdit_6_4->setObjectName("lineEdit_6_4");
        lineEdit_6_4->setGeometry(QRect(420, 580, 91, 91));
        lineEdit_6_4->setFont(font4);
        lineEdit_6_4->setMaxLength(1);
        lineEdit_6_4->setAlignment(Qt::AlignCenter);
        lineEdit_6_1 = new QLineEdit(centralwidget);
        lineEdit_6_1->setObjectName("lineEdit_6_1");
        lineEdit_6_1->setGeometry(QRect(150, 580, 91, 91));
        lineEdit_6_1->setFont(font4);
        lineEdit_6_1->setMaxLength(1);
        lineEdit_6_1->setAlignment(Qt::AlignCenter);
        lineEdit_6_6 = new QLineEdit(centralwidget);
        lineEdit_6_6->setObjectName("lineEdit_6_6");
        lineEdit_6_6->setGeometry(QRect(600, 580, 91, 91));
        lineEdit_6_6->setFont(font4);
        lineEdit_6_6->setMaxLength(1);
        lineEdit_6_6->setAlignment(Qt::AlignCenter);
        lineEdit_6_7 = new QLineEdit(centralwidget);
        lineEdit_6_7->setObjectName("lineEdit_6_7");
        lineEdit_6_7->setGeometry(QRect(690, 580, 91, 91));
        lineEdit_6_7->setFont(font4);
        lineEdit_6_7->setMaxLength(1);
        lineEdit_6_7->setAlignment(Qt::AlignCenter);
        lineEdit_6_3 = new QLineEdit(centralwidget);
        lineEdit_6_3->setObjectName("lineEdit_6_3");
        lineEdit_6_3->setGeometry(QRect(330, 580, 91, 91));
        lineEdit_6_3->setFont(font4);
        lineEdit_6_3->setMaxLength(1);
        lineEdit_6_3->setAlignment(Qt::AlignCenter);
        lineEdit_6_5 = new QLineEdit(centralwidget);
        lineEdit_6_5->setObjectName("lineEdit_6_5");
        lineEdit_6_5->setGeometry(QRect(510, 580, 91, 91));
        lineEdit_6_5->setFont(font4);
        lineEdit_6_5->setMaxLength(1);
        lineEdit_6_5->setAlignment(Qt::AlignCenter);
        lineEdit_6_0 = new QLineEdit(centralwidget);
        lineEdit_6_0->setObjectName("lineEdit_6_0");
        lineEdit_6_0->setGeometry(QRect(60, 580, 91, 91));
        lineEdit_6_0->setFont(font4);
        lineEdit_6_0->setMaxLength(1);
        lineEdit_6_0->setAlignment(Qt::AlignCenter);
        lineEdit_6_8 = new QLineEdit(centralwidget);
        lineEdit_6_8->setObjectName("lineEdit_6_8");
        lineEdit_6_8->setGeometry(QRect(780, 580, 91, 91));
        lineEdit_6_8->setFont(font4);
        lineEdit_6_8->setMaxLength(1);
        lineEdit_6_8->setAlignment(Qt::AlignCenter);
        lineEdit_7_2 = new QLineEdit(centralwidget);
        lineEdit_7_2->setObjectName("lineEdit_7_2");
        lineEdit_7_2->setGeometry(QRect(240, 670, 91, 91));
        lineEdit_7_2->setFont(font4);
        lineEdit_7_2->setMaxLength(1);
        lineEdit_7_2->setAlignment(Qt::AlignCenter);
        lineEdit_7_4 = new QLineEdit(centralwidget);
        lineEdit_7_4->setObjectName("lineEdit_7_4");
        lineEdit_7_4->setGeometry(QRect(420, 670, 91, 91));
        lineEdit_7_4->setFont(font4);
        lineEdit_7_4->setMaxLength(1);
        lineEdit_7_4->setAlignment(Qt::AlignCenter);
        lineEdit_7_1 = new QLineEdit(centralwidget);
        lineEdit_7_1->setObjectName("lineEdit_7_1");
        lineEdit_7_1->setGeometry(QRect(150, 670, 91, 91));
        lineEdit_7_1->setFont(font4);
        lineEdit_7_1->setMaxLength(1);
        lineEdit_7_1->setAlignment(Qt::AlignCenter);
        lineEdit_7_6 = new QLineEdit(centralwidget);
        lineEdit_7_6->setObjectName("lineEdit_7_6");
        lineEdit_7_6->setGeometry(QRect(600, 670, 91, 91));
        lineEdit_7_6->setFont(font4);
        lineEdit_7_6->setMaxLength(1);
        lineEdit_7_6->setAlignment(Qt::AlignCenter);
        lineEdit_7_7 = new QLineEdit(centralwidget);
        lineEdit_7_7->setObjectName("lineEdit_7_7");
        lineEdit_7_7->setGeometry(QRect(690, 670, 91, 91));
        lineEdit_7_7->setFont(font4);
        lineEdit_7_7->setMaxLength(1);
        lineEdit_7_7->setAlignment(Qt::AlignCenter);
        lineEdit_7_3 = new QLineEdit(centralwidget);
        lineEdit_7_3->setObjectName("lineEdit_7_3");
        lineEdit_7_3->setGeometry(QRect(330, 670, 91, 91));
        lineEdit_7_3->setFont(font4);
        lineEdit_7_3->setMaxLength(1);
        lineEdit_7_3->setAlignment(Qt::AlignCenter);
        lineEdit_7_5 = new QLineEdit(centralwidget);
        lineEdit_7_5->setObjectName("lineEdit_7_5");
        lineEdit_7_5->setGeometry(QRect(510, 670, 91, 91));
        lineEdit_7_5->setFont(font4);
        lineEdit_7_5->setMaxLength(1);
        lineEdit_7_5->setAlignment(Qt::AlignCenter);
        lineEdit_7_0 = new QLineEdit(centralwidget);
        lineEdit_7_0->setObjectName("lineEdit_7_0");
        lineEdit_7_0->setGeometry(QRect(60, 670, 91, 91));
        lineEdit_7_0->setFont(font4);
        lineEdit_7_0->setMaxLength(1);
        lineEdit_7_0->setAlignment(Qt::AlignCenter);
        lineEdit_7_8 = new QLineEdit(centralwidget);
        lineEdit_7_8->setObjectName("lineEdit_7_8");
        lineEdit_7_8->setGeometry(QRect(780, 670, 91, 91));
        lineEdit_7_8->setFont(font4);
        lineEdit_7_8->setMaxLength(1);
        lineEdit_7_8->setAlignment(Qt::AlignCenter);
        lineEdit_8_2 = new QLineEdit(centralwidget);
        lineEdit_8_2->setObjectName("lineEdit_8_2");
        lineEdit_8_2->setGeometry(QRect(240, 760, 91, 91));
        lineEdit_8_2->setFont(font4);
        lineEdit_8_2->setMaxLength(1);
        lineEdit_8_2->setAlignment(Qt::AlignCenter);
        lineEdit_8_4 = new QLineEdit(centralwidget);
        lineEdit_8_4->setObjectName("lineEdit_8_4");
        lineEdit_8_4->setGeometry(QRect(420, 760, 91, 91));
        lineEdit_8_4->setFont(font4);
        lineEdit_8_4->setMaxLength(1);
        lineEdit_8_4->setAlignment(Qt::AlignCenter);
        lineEdit_8_1 = new QLineEdit(centralwidget);
        lineEdit_8_1->setObjectName("lineEdit_8_1");
        lineEdit_8_1->setGeometry(QRect(150, 760, 91, 91));
        lineEdit_8_1->setFont(font4);
        lineEdit_8_1->setMaxLength(1);
        lineEdit_8_1->setAlignment(Qt::AlignCenter);
        lineEdit_8_6 = new QLineEdit(centralwidget);
        lineEdit_8_6->setObjectName("lineEdit_8_6");
        lineEdit_8_6->setGeometry(QRect(600, 760, 91, 91));
        lineEdit_8_6->setFont(font4);
        lineEdit_8_6->setMaxLength(1);
        lineEdit_8_6->setAlignment(Qt::AlignCenter);
        lineEdit_8_7 = new QLineEdit(centralwidget);
        lineEdit_8_7->setObjectName("lineEdit_8_7");
        lineEdit_8_7->setGeometry(QRect(690, 760, 91, 91));
        lineEdit_8_7->setFont(font4);
        lineEdit_8_7->setMaxLength(1);
        lineEdit_8_7->setAlignment(Qt::AlignCenter);
        lineEdit_8_3 = new QLineEdit(centralwidget);
        lineEdit_8_3->setObjectName("lineEdit_8_3");
        lineEdit_8_3->setGeometry(QRect(330, 760, 91, 91));
        lineEdit_8_3->setFont(font4);
        lineEdit_8_3->setMaxLength(1);
        lineEdit_8_3->setAlignment(Qt::AlignCenter);
        lineEdit_8_5 = new QLineEdit(centralwidget);
        lineEdit_8_5->setObjectName("lineEdit_8_5");
        lineEdit_8_5->setGeometry(QRect(510, 760, 91, 91));
        lineEdit_8_5->setFont(font4);
        lineEdit_8_5->setMaxLength(1);
        lineEdit_8_5->setAlignment(Qt::AlignCenter);
        lineEdit_8_0 = new QLineEdit(centralwidget);
        lineEdit_8_0->setObjectName("lineEdit_8_0");
        lineEdit_8_0->setGeometry(QRect(60, 760, 91, 91));
        lineEdit_8_0->setFont(font4);
        lineEdit_8_0->setMaxLength(1);
        lineEdit_8_0->setAlignment(Qt::AlignCenter);
        lineEdit_8_8 = new QLineEdit(centralwidget);
        lineEdit_8_8->setObjectName("lineEdit_8_8");
        lineEdit_8_8->setGeometry(QRect(780, 760, 91, 91));
        lineEdit_8_8->setFont(font4);
        lineEdit_8_8->setMaxLength(1);
        lineEdit_8_8->setAlignment(Qt::AlignCenter);
        lineEdit_3_7 = new QLineEdit(centralwidget);
        lineEdit_3_7->setObjectName("lineEdit_3_7");
        lineEdit_3_7->setGeometry(QRect(690, 310, 91, 91));
        lineEdit_3_7->setFont(font4);
        lineEdit_3_7->setMaxLength(1);
        lineEdit_3_7->setAlignment(Qt::AlignCenter);
        lineEdit_3_5 = new QLineEdit(centralwidget);
        lineEdit_3_5->setObjectName("lineEdit_3_5");
        lineEdit_3_5->setGeometry(QRect(510, 310, 91, 91));
        lineEdit_3_5->setFont(font4);
        lineEdit_3_5->setMaxLength(1);
        lineEdit_3_5->setAlignment(Qt::AlignCenter);
        lineEdit_3_6 = new QLineEdit(centralwidget);
        lineEdit_3_6->setObjectName("lineEdit_3_6");
        lineEdit_3_6->setGeometry(QRect(600, 310, 91, 91));
        lineEdit_3_6->setFont(font4);
        lineEdit_3_6->setMaxLength(1);
        lineEdit_3_6->setAlignment(Qt::AlignCenter);
        lineEdit_3_4 = new QLineEdit(centralwidget);
        lineEdit_3_4->setObjectName("lineEdit_3_4");
        lineEdit_3_4->setGeometry(QRect(420, 310, 91, 91));
        lineEdit_3_4->setFont(font4);
        lineEdit_3_4->setMaxLength(1);
        lineEdit_3_4->setAlignment(Qt::AlignCenter);
        lineEdit_3_8 = new QLineEdit(centralwidget);
        lineEdit_3_8->setObjectName("lineEdit_3_8");
        lineEdit_3_8->setGeometry(QRect(780, 310, 91, 91));
        lineEdit_3_8->setFont(font4);
        lineEdit_3_8->setMaxLength(1);
        lineEdit_3_8->setAlignment(Qt::AlignCenter);
        lineEdit_0_1 = new QLineEdit(centralwidget);
        lineEdit_0_1->setObjectName("lineEdit_0_1");
        lineEdit_0_1->setGeometry(QRect(150, 40, 91, 91));
        lineEdit_0_1->setFont(font4);
        lineEdit_0_1->setMaxLength(1);
        lineEdit_0_1->setAlignment(Qt::AlignCenter);
        SudokuMaster->setCentralWidget(centralwidget);
        lineEdit_0_0->raise();
        lineEdit_0_2->raise();
        line_10->raise();
        lineEdit_0_3->raise();
        lineEdit_0_4->raise();
        lineEdit_0_5->raise();
        lineEdit_0_6->raise();
        lineEdit_0_7->raise();
        lineEdit_0_8->raise();
        lineEdit_1_0->raise();
        lineEdit_1_1->raise();
        lineEdit_1_2->raise();
        lineEdit_2_0->raise();
        lineEdit_2_1->raise();
        lineEdit_2_2->raise();
        lineEdit_1_3->raise();
        lineEdit_1_4->raise();
        lineEdit_1_5->raise();
        lineEdit_2_3->raise();
        lineEdit_2_4->raise();
        lineEdit_2_5->raise();
        lineEdit_1_6->raise();
        lineEdit_1_7->raise();
        lineEdit_1_8->raise();
        lineEdit_2_6->raise();
        lineEdit_2_7->raise();
        lineEdit_2_8->raise();
        lineEdit_3_0->raise();
        lineEdit_3_1->raise();
        lineEdit_3_2->raise();
        lineEdit_3_3->raise();
        lineEdit_4_2->raise();
        lineEdit_4_4->raise();
        lineEdit_4_1->raise();
        lineEdit_4_6->raise();
        lineEdit_4_7->raise();
        lineEdit_4_3->raise();
        lineEdit_4_5->raise();
        lineEdit_4_0->raise();
        lineEdit_4_8->raise();
        lineEdit_5_2->raise();
        lineEdit_5_4->raise();
        lineEdit_5_1->raise();
        lineEdit_5_6->raise();
        lineEdit_5_7->raise();
        lineEdit_5_3->raise();
        lineEdit_5_5->raise();
        lineEdit_5_0->raise();
        lineEdit_5_8->raise();
        lineEdit_6_2->raise();
        lineEdit_6_4->raise();
        lineEdit_6_1->raise();
        lineEdit_6_6->raise();
        lineEdit_6_7->raise();
        lineEdit_6_3->raise();
        lineEdit_6_5->raise();
        lineEdit_6_0->raise();
        lineEdit_6_8->raise();
        lineEdit_7_2->raise();
        lineEdit_7_4->raise();
        lineEdit_7_1->raise();
        lineEdit_7_6->raise();
        lineEdit_7_7->raise();
        lineEdit_7_3->raise();
        lineEdit_7_5->raise();
        lineEdit_7_0->raise();
        lineEdit_7_8->raise();
        lineEdit_8_2->raise();
        lineEdit_8_4->raise();
        lineEdit_8_1->raise();
        lineEdit_8_6->raise();
        lineEdit_8_7->raise();
        lineEdit_8_3->raise();
        lineEdit_8_5->raise();
        lineEdit_8_0->raise();
        lineEdit_8_8->raise();
        line_11->raise();
        line_12->raise();
        line_13->raise();
        line_2->raise();
        line_18->raise();
        line_16->raise();
        line_4->raise();
        line_19->raise();
        line_20->raise();
        lineEdit_3_7->raise();
        lineEdit_3_5->raise();
        lineEdit_3_6->raise();
        lineEdit_3_4->raise();
        lineEdit_3_8->raise();
        line_8->raise();
        line_5->raise();
        line_9->raise();
        line_6->raise();
        line_14->raise();
        line_7->raise();
        line_15->raise();
        line_17->raise();
        lineEdit_0_1->raise();
        line_3->raise();
        line->raise();
        menubar = new QMenuBar(SudokuMaster);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 930, 36));
        SudokuMaster->setMenuBar(menubar);
        statusbar = new QStatusBar(SudokuMaster);
        statusbar->setObjectName("statusbar");
        SudokuMaster->setStatusBar(statusbar);
        QWidget::setTabOrder(lineEdit_0_2, lineEdit_0_0);

        retranslateUi(SudokuMaster);

        QMetaObject::connectSlotsByName(SudokuMaster);
    } // setupUi

    void retranslateUi(QMainWindow *SudokuMaster)
    {
        SudokuMaster->setWindowTitle(QCoreApplication::translate("SudokuMaster", "SudokuMaster", nullptr));
    } // retranslateUi

};

namespace Ui {
    class SudokuMaster: public Ui_SudokuMaster {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SUDOKUMASTER_H
